name: Build Python Wheels

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build
      - name: Build wheel
        run: pip wheel .
      - name: Upload wheel
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }} ${{ matrix.python-version }} pyuasrisk wheel
          path: ${{ github.workspace }}/*.whl

          
